import "./globals.css";
import "react-day-picker/dist/style.css";
import {Inter} from "next/font/google";
import Navigation from "@/components/Navigation";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation></Navigation>
        {children}
      </body>
    </html>
  );
}
